version:  '3'
services:
  redis:
    image: "redis:alpine"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  node:
      build: .
      volumes:
        - ./:/usr/src/app
      working_dir: /usr/src/app
      ports:
        - 3000:3000
      environment:
          DEBUG: 'true'
      command: npm run dev
      links:
        - mongo
        - redis
  webpack:
    build: 
      context: ./.docker/webpack
    ports:
      - 8080
    volumes:
      - "./client:/app/client"
    command: "npm start"
  nginx:
    build:
      context: ./.docker/nginx
    restart: unless-stopped
    depends_on:
      - webpack
    ports:
      - 8000:80
    volumes:
      - "./client/dist:/usr/share/nginx/html"


